apiVersion: apps/v1
kind: Deployment
metadata:
  name: janitor
  labels:
    app: janitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: janitor
  template:
    metadata:
      labels:
        app: janitor
    spec:
      imagePullSecrets:
      - name: headless-commerce-package-access-token
      containers:
      - name: janitor
        image: ghcr.io/headless-commerce/janitor
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /health/live
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 120
        envFrom:
        - secretRef:
            name: janitor-secrets
        env:
        - name: JANITOR_DB_USER
          value: 'janitor'
        - name: JANITOR_DB_NAME
          value: 'janitor'
        - name: JANITOR_DB_HOST
          value: 'mysql'
        - name: JANITOR_DB_POOL_SIZE
          value: '5'
        - name: JANITOR_DNS_HOST
          value: 'janitor.moview.com.ng'
        - name: JANITOR_PORT
          value: '4000'
---
kind: Service
apiVersion: v1
metadata:
  name: janitor
  labels:
    app: janitor
    release: kube-prometheus-stack
spec:
  ports:
  - name: web
    port: 80
    targetPort: 4000
  selector:
    app: janitor