apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: janitor-secrets
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: janitor-secrets
  data:
  - secretKey: dbPass
    remoteRef:
      key: secret/janitor
      property: db_pass
  - secretKey: secretKeyBase
    remoteRef:
      key: secret/janitor
      property: key_base
  - secretKey: bucketId
    remoteRef:
      key: secret/janitor
      property: bucket_id
  - secretKey: bucketName
    remoteRef:
      key: secret/janitor
      property: bucket_name
  - secretKey: bucketAccessKey
    remoteRef:
      key: secret/janitor
      property: bucket_access_key
  - secretKey: bucketAccessKeyId
    remoteRef:
      key: secret/janitor
      property: bucket_access_key_id
  - secretKey: superuserPassword
    remoteRef:
      key: secret/janitor
      property: superuser_password