apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: janitor-secrets
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: janitor-secrets
  data:
  - secretKey: dbPass
    remoteRef:
      key: secret/janitor/db-pass
      property: value
  - secretKey: secretKeyBase
    remoteRef:
      key: secret/janitor/secret-key-base
      property: value
  - secretKey: bucketId
    remoteRef:
      key: secret/janitor/bucket-id
      property: value
  - secretKey: bucketName
    remoteRef:
      key: secret/janitor/bucket-name
      property: value
  - secretKey: bucketAccessKey
    remoteRef:
      key: secret/janitor/bucket-access-key
      property: value
  - secretKey: bucketAccessKeyId
    remoteRef:
      key: secret/janitor/bucket-access-key-id
      property: value
  - secretKey: superuserPassword
    remoteRef:
      key: secret/janitor/superuser-password
      property: value