apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: janitor-secrets
spec:
  refreshInterval: "6h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: janitor-secrets
  data:
  - secretKey: JANITOR_DB_PASS
    remoteRef:
      key: secret/janitor
      property: db_pass
  - secretKey: JANITOR_SECRET_KEY_BASE
    remoteRef:
      key: secret/janitor
      property: key_base
  - secretKey: JANITOR_BUCKET_ID
    remoteRef:
      key: secret/janitor
      property: bucket_id
  - secretKey: JANITOR_BUCKET_NAME
    remoteRef:
      key: secret/janitor
      property: bucket_name
  - secretKey: JANITOR_BUCKET_ACCESS_KEY
    remoteRef:
      key: secret/janitor
      property: bucket_access_key
  - secretKey: JANITOR_BUCKET_ACCESS_KEY_ID
    remoteRef:
      key: secret/janitor
      property: bucket_access_key_id
  - secretKey: JANITOR_SUPERUSER_PASSWORD
    remoteRef:
      key: secret/janitor
      property: superuser_password